name: ci

on:
  push:
    branches:
      - grammar_optimization
    paths:
      - 'src/**'
      - 'test/**'
      - 'grammars/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
  pull_request:
    branches:
      - main
      - grammar_optimization
    paths:
      - 'src/**'
      - 'test/**'
      - 'grammars/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  grammar_test:
    name: SGL Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Running test script
        run: ./scripts/test.sh
